language: node_js
node_js:
  - '8.10'
  - '8'
  - '10'
  - '12'
install:
  - npm install
  - (cd example && npm install)
script:
  - npm run lint
  - npm test
  - npm run integration-tests
cache: npm
